apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: tmuehlba/udagram-api-feed:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"   # 200 milli-cores (0.2 CPU)
          limits:
            cpu: "500m"   # Maximale CPU-Nutzung von 500 milli-cores (0.5 CPU)
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: tmuehlba/udagram-api-user:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"   # 200 milli-cores (0.2 CPU)
          limits:
            cpu: "500m"   # Maximale CPU-Nutzung von 500 milli-cores (0.5 CPU)
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secret
        - secretRef:
            name: aws-secret

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tmuehlba/udagram-frontend:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"   # 100 milli-cores (0.1 CPU)
          limits:
            cpu: "300m"   # Maximale CPU-Nutzung von 300 milli-cores (0.3 CPU)
        envFrom:
        - configMapRef:
            name: env-configmap


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: tmuehlba/reverseproxy:v1
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"   # 100 milli-cores (0.1 CPU)
          limits:
            cpu: "300m"   # Maximale CPU-Nutzung von 300 milli-cores (0.3 CPU)
        envFrom:
        - configMapRef:
            name: env-configmap

