apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  type: ClusterIP
  selector:
    app: backend-feed
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  type: ClusterIP
  selector:
    app: backend-user
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  type: ClusterIP
  selector:
    app: reverseproxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
